import mongoose, { AnyExpression } from "mongoose";
import staffAuth from "../../../model/staff/staffAuth";
import adminAuth from "../../../model/admin/adminAuth";
import express, { Request, Response } from "express";
import adminWalletModel from "../../../model/admin/admindashboard/adminWallets";
import adminTransactionHistory from "../../../model/admin/admindashboard/adminTransactionHistorys";
import staffTransactionHistory from "../../../model/staff/staffDashboard/stafftransactionHistorys";
import staffWalletModel from "../../../model/staff/staffDashboard/StaffWallet";
import houseModel from "../../../model/staff/staffDashboard/StaffHouse";
import crypto from "crypto";
import { v4 as uuid } from "uuid";
import axios from "axios";
import travelModel from "../../../model/staff/staffDashboard/staffTravel";
import feesModel from "../../../model/staff/staffDashboard/staffFees";
